name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Download ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
      
    - name: Extract ngrok
      run: Expand-Archive -Path ngrok.zip -DestinationPath .
      
    - name: Auth ngrok
      run: .\ngrok.exe authtoken 33YRiHe7UOwDPK8j1Q1xdImUvGk_7UQdSxqQMvy4GfYc1kRjN
      
    - name: Enable Remote Desktop
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
      
    - name: Configure Firewall
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      
    - name: Configure RDP Authentication
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      
    - name: Set RDP Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      
    - name: Create ngrok Tunnel
      run: .\ngrok.exe tcp 3389
